include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/reuse-lint.yml"

lint-shellcheck:
  stage: lint
  image: koalaman/shellcheck-alpine:latest
  tags:
    - host-arm64
    - self-hosted
  script:
    - find . -name "*.sh" | xargs shellcheck
